-- no-transaction
CREATE TABLE IF NOT EXISTS users(
    id NUMERIC(20, 0) NOT NULL PRIMARY KEY, -- u64
    links TEXT,
    link_guilds TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
