#!/bin/bash

set -euo pipefail

OWN_FILENAME="$(basename $0)"
LAMBDA_EXTENSION_NAME="$OWN_FILENAME" # (external) extension name has to match the filename

echo "${LAMBDA_EXTENSION_NAME} launching extension"
cd /opt
exec python3 extensions/dislord_ext.py -X importtime