name: Serverless Package & Upload 📦🪣
on: push
permissions:
  contents: read

jobs:
  package-api:
    name: Package API Zip 📦
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Install dependencies
        run: pip install cargo-lambda
      - name: Build
        run: |
          cd api
          cargo lambda build --release --output-format zip

      - name: Upload to Lambda
        run: |
          aws lambda update-function-code --function-name kb2-lambda-function-dev --zip-file fileb://api/target/lambda/api/bootstrap.zip