name: Serverless Package & Upload 📦🪣
on: push

jobs:
  build:
    name: Package Zip 📦
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"


    - name: Install pip requirements
      run: |
        mkdir package
        pip install -r requirements.txt --target ./package
        cd package
        zip -r ../package.zip .
        cd ..

    - name: Add project code
      run: |
        zip -r ./package.zip ./dislord
        zip -r ./package.zip ./kb2

    - uses: actions/upload-artifact@v3
      with:
        name: sl-package
        path: ./package.zip

  upload-s3:
    name: Upload to S3 🪣
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: sl-package

    - name: Setup AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2

    - name: Deploy Modified Files
      run: |
        ls
        # Constants
        S3_BUCKET=kb2
        S3_KEY=package.zip
        aws s3 cp package.zip s3://$S3_BUCKET/$S3_KEY
        # Update Lambda function code
        LAMBDA_FUNCTION_NAME=KB2
        aws lambda update-function-code --function-name $LAMBDA_FUNCTION_NAME --s3-bucket $S3_BUCKET --s3-key $S3_KEY
        LAMBDA_FUNCTION_NAME=KB2-Sync
        aws lambda update-function-code --function-name $LAMBDA_FUNCTION_NAME --s3-bucket $S3_BUCKET --s3-key $S3_KEY


